TubNet2/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLibrary;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using TubNet2.Models;


namespace TubNet2.Controllers
{
    public class PatientController : Controller
    {

        private TubDataBaseEntities db = new TubDataBaseEntities();
        private static ViewPatientsModel model;

        // GET: Patient
        public ActionResult PatientsTable()
        {
            if (model == null)
            {
                model = new ViewPatientsModel();
                model.collection = db.Patients
                    .Include(c => c.Gender).ToList();
                model.filter = new PatientsFilterModel();

            }
            else
            {
                model.collection = FilterPatient();
            }


            SelectList gender = new SelectList(db.Gender.ToList(), "gen_id", "gen_value");
            ViewBag.Gender = gender;
            SelectList diagnosis = new SelectList(db.Diagnosis, "diag_id", "diag_value");
            ViewBag.Diagnosis = diagnosis;
            SelectList type = new SelectList(db.Type, "type_id", "type_value");
            ViewBag.Type = type;
            SelectList bk = new SelectList(db.BK, "bk_id", "bk_value");
            ViewBag.BK = bk;
            SelectList dest = new SelectList(db.Destruction, "destr_id", "destr_value");
            ViewBag.Destruction = dest;
            return View(model);
        }

        [HttpPost]
        public ActionResult SetFilter(PatientsFilterModel f)
        {
            model.filter = f;
            return RedirectToAction("PatientsTable");
        }

        private List<Patients> FilterPatient()
        {
            PrepareFilter();
            PatientsFilterModel f = model.filter;
            var query = (from q in db.Patients select q);
            if (f.p_surname!=null)
            {
                query = query.Where(q => q.p_surname.Contains(f.p_surname));
            }
            if (f.p_name != null)
            {
                query = query.Where(q => q.p_name.Contains(f.p_name));
            }
            if (f.p_secname != null)
            {
                query = query.Where(q => q.p_secname.Contains(f.p_secname));
            }
            if (f.UseBirthday == true)
            {
                query = query.Where(q => q.p_birthday == f.p_birthday);
            }
            if (f.UseGender == true)
            {
                query = query.Where(q => q.p_genderId == f.p_genderId);
            }
            if (f.UseDiagnosis == true)
            {
                query = query.Where(q => q.p_diagnosisId == f.p_diagnosisId);
            }
            if (f.UseType == true)
            {
                query = query.Where(q => q.p_typeId == f.p_typeId);
            }
            if (f.UseBK == true)
            {
                query = query.Where(q => q.p_bkID == f.p_bkID);
            }
            if (f.UseDestruction == true)
            {
                query = query.Where(q => q.p_destructionId == f.p_destructionId);
            }
            return query.ToList();
        }

        private void PrepareFilter()
        {
            if (model.filter.p_surname != null)
            {
                model.filter.p_surname = model.filter.p_surname.Trim();
            }
            if (model.filter.p_name != null)
            {
                model.filter.p_name = model.filter.p_name.Trim();
            }
            if (model.filter.p_secname != null)
            {
                model.filter.p_secname = model.filter.p_secname.Trim();
            }
        }

        [HttpGet]
        public ActionResult AddPatient()
        {
            SelectList gender = new SelectList(db.Gender, "gen_id", "gen_value");
            ViewBag.Gender = gender;
            SelectList diagnosis = new SelectList(db.Diagnosis, "diag_id", "diag_value");
            ViewBag.Diagnosis = diagnosis;
            SelectList type = new SelectList(db.Type, "type_id", "type_value");
            ViewBag.Type = type;
            SelectList bk = new SelectList(db.BK, "bk_id", "bk_value");
            ViewBag.BK = bk;
            SelectList dest = new SelectList(db.Destruction, "destr_id", "destr_value");
            ViewBag.Destruction = dest;
            return View();
        }

        [HttpPost]
        public ActionResult AddPatient(Patients p)
        {
            if(ModelState.IsValid)
            {
                db.Patients.Add(p);
                db.SaveChanges();

                return RedirectToAction("PatientsTable");
            }
            else
            {
                return View(p);
            }
        }

        public ActionResult SinglePatient(int p_id = 0)
        {
           
            Patients pat = (from p in db.Patients where (p.p_id == p_id) select p).FirstOrDefault();
            if (pat==null)
            {
                return HttpNotFound();
            }
            return View(pat);
        }

        [HttpGet]
        public ActionResult SinglePatientEdit(int p_id = 0)
        {
            db = new TubDataBaseEntities();
            
            SelectList gender = new SelectList(db.Gender.ToList(), "gen_id", "gen_value");
            ViewBag.Gender = gender;
            SelectList diagnosis = new SelectList(db.Diagnosis, "diag_id", "diag_value");
            ViewBag.Diagnosis = diagnosis;
            SelectList type = new SelectList(db.Type, "type_id", "type_value");
            ViewBag.Type = type;
            SelectList bk = new SelectList(db.BK, "bk_id", "bk_value");
            ViewBag.BK = bk;
            SelectList dest = new SelectList(db.Destruction, "destr_id", "destr_value");
            ViewBag.Destruction = dest;

            Patients pat = (from p in db.Patients where (p.p_id == p_id) select p).FirstOrDefault();
            if (pat == null)
            {
                return HttpNotFound();
            }
            return View(pat);
        }

        [HttpPost]
        public ActionResult SinglePatientEdit(Patients update)
        {
            if (ModelState.IsValid)
            {
                Patients pat = (from p in db.Patients where p.p_id == update.p_id select p).FirstOrDefault();
                pat.p_surname = update.p_surname.Trim();
                pat.p_name = update.p_name.Trim();
                pat.p_secname = update.p_secname.Trim();
                pat.p_birthday = update.p_birthday;
                pat.p_genderId = update.p_genderId;
                pat.p_factAddress = update.p_factAddress;
                pat.p_regAddress = update.p_regAddress;
                pat.p_phones = update.p_phones;
                pat.p_diagnosisId = update.p_diagnosisId;
                pat.p_typeId = update.p_typeId;
                pat.p_bkID = update.p_bkID;
                pat.p_destructionId = update.p_destructionId;
                pat.p_otherDiseases = update.p_otherDiseases;
                pat.p_firstVisit = update.p_firstVisit;
                pat.p_lastVisit = update.p_lastVisit;
                pat.p_result = update.p_result;
                pat.p_komment = update.p_komment;
                db.SaveChanges();
                return RedirectToAction("PatientsTable");
            }
            else
            {
                return View(update);
            }
        }

        public ActionResult SinglePatientDelete(int p_id)
        {
            Patients pat = (from p in db.Patients where p.p_id == p_id select p).FirstOrDefault();
            db.Patients.Remove(pat);
            db.SaveChanges();

            return RedirectToAction("PatientsTable");
        }
    }
}

TubNet2/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLibrary;
using TubNet2.Models;
using System.Data.Entity;
using TubNet2.ControllerHelpers;

namespace TubNet2.Controllers
{
    public class TestController : Controller
    {
        private TubDataBaseEntities db = new TubDataBaseEntities();
        private static int pid = 0;
        private static ViewTestsModel model;
        private static int activeTest;
        private static SelectList ConsType;

        // GET: Test
        public ActionResult TestsList(int p_id = 0, string viewName = "BloodTest", string type = "Plan")
        {
            pid = p_id;
            if (model == null || model.ViewName!=viewName)
            {
                model = new ViewTestsModel();
                ConsType = new SelectList(db.ConsultationType, "ct_id", "ct_value");
            }
            if (model.filter == null)
            {
                model.filter = new FilterModel();

            }

                ViewBag.SelectType = ConsType;

            Patients pat = (from p in db.Patients where p.p_id == p_id select p).FirstOrDefault();
            model.Patient = pat;
            model.ViewName = viewName;
            model.ViewCollection = GetList(viewName, type, p_id);
            model.filter.ViewType = type;
            return View(model);
        }

        [HttpPost]
        public ActionResult Filter(FilterModel filter = null)
        {
            if (filter.UseDate == false)
            {
                model.filter.UseDate = false;
                model.filter.borderDate = null;
                model.filter.ViewType = filter.ViewType;
            }
            else
            {
                model.filter.ViewType = filter.ViewType;
                model.filter.borderDate = filter.borderDate;
                model.filter.UseDate = true;
            }
          
            return redirect();
        }

        public ActionResult PlanTest(DateTime date)
        {
            HelperSelector.get(model.ViewName).PlanNewTest(date, pid);
            return redirect();
        }

        public ActionResult PlanConsultation(DateTime date, int ct_id)
        {
            ((ConsultationHelper)HelperSelector.get("Consultation")).PlanNewTest(date, ct_id, pid);
            return redirect();
        }

        [HttpPost]
        public ActionResult UpdateBloodTest(BloodTest blood)
        {
            HelperSelector.get(model.ViewName).UpdateTest(blood);
            model.Single = null;
            return redirect();
        }

        [HttpPost]
        public ActionResult UpdateUrinaTest(UrineTest urina)
        {
            HelperSelector.get(model.ViewName).UpdateTest(urina);
            model.Single = null;
            return redirect();
        }

        [HttpPost]
        public ActionResult UpdateHepaticTest(HepaticTest hepat)
        {
            HelperSelector.get(model.ViewName).UpdateTest(hepat);
            model.Single = null;
            return redirect();
        }

        [HttpPost]
        public ActionResult UpdateSputumTest(SputumTest sputum)
        {
            HelperSelector.get(model.ViewName).UpdateTest(sputum);
            model.Single = null;
            return redirect();
        }

        [HttpPost]
        public ActionResult UpdateConsultation(Consultation consultation)
        {
            HelperSelector.get(model.ViewName).UpdateTest(consultation);
            model.Single = null;
            return redirect();
        }

        public ActionResult DeleteTest(int id = 0)
        {
            int a = HelperSelector.get(model.ViewName).DeleteTest(id);
            if(a == activeTest)
            {
                model.Single = null;
            }
            return redirect();
        }

        public ActionResult ChangeActiveTest(int id = 0)
        {
            model.Single = HelperSelector.get(model.ViewName).GetActiveTest(id);
            model.SingleDate = HelperSelector.get(model.ViewName).GetActiveTestDate(id);
            activeTest = id;
            return redirect();
        }

        private RedirectToRouteResult redirect()
        {
            return RedirectToAction("TestsList", new { p_id = model.Patient.p_id, viewName = model.ViewName, type = model.filter.ViewType });
        }

        private object GetList(string view, string type, int p_id)
        {
            string sort = "";
            switch(type)
            {
                case "Close": sort = "завершено";
                    break;
                case "Plan":sort = "заплановано";
                    break;
                case "Lose":sort = "пропущено";
                    break;
            }
            if (model.filter.borderDate == null)
            {
                return HelperSelector.get(view).GetSortedCollection(sort, p_id);
            }
            else
            {
                return HelperSelector.get(view).GetSortedCollection(sort, p_id, model.filter.borderDate ?? default(DateTime));
            }
        }
    }
}

TubNet2/Views/Test/Close.cshtml
@model TubNet2.Models.ViewTestsModel

<div class="col-md-12">
    <h3>Завершені аналізи</h3>
</div>
<div class="col-md-12">
    @Html.Partial(String.Format("Partials/{0}/FullTable", Model.ViewName), Model.ViewCollection)
</divclass="col-md-12">

TubNet2/Views/Test/Lose.cshtml
@model TubNet2.Models.ViewTestsModel

<div class="col-md-6">
        <h3>Пропущені аналізи</h3>
        @Html.Partial(String.Format("Partials/{0}/LoseTable", Model.ViewName), Model.ViewCollection)
</div>
<div class="col-md-6 test-field">
    @if (Model.Single != null)
    {
        <div class="title">
            <h4>Аналіз за @Model.SingleDate</h4>
        </div>
        @Html.Partial(String.Format("Partials/{0}/{0}", Model.ViewName), Model.Single)
    }
    else
    {
        <div class="empty-test">
            <h2>Аналіз не обрано</h2>
        </div>
    }
</div>

TubNet2/Views/Test/Plan.cshtml
@model TubNet2.Models.ViewTestsModel

<style>

</style>

<div  class="col-md-6">
    <div class="plan-button">
        <h4>Запланувати новий аналіз на </h4>
        @if (Model.ViewName != "Consultation")
    {

        using (Html.BeginForm("PlanTest", "Test", FormMethod.Post, htmlAttributes: new { @class = "form" }))
        {
            <input type="date" name="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" min="@DateTime.Today.ToString("yyyy-MM-dd")" class=" col-md-6 form-control" />
            <input type="submit" value="ОК" class="btn btn-style" />
    }

}
else
{
    using (Html.BeginForm("PlanConsultation", "Test", FormMethod.Post, htmlAttributes: new { @class = "form" }))
    {
        <input type="date" name="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" min="@DateTime.Today.ToString("yyyy-MM-dd")" class=" col-md-6 form-control" />
        <br />
        <br />
        @Html.DropDownList("ct_id", ViewBag.SelectType as SelectList, htmlAttributes:new { @class="col-md-12"})
        <br />
        <br />
        <input type="submit" value="ОК" class="btn btn-style" />
}
}
    </div>
    <div>
        <h3>Заплановані аналізи</h3>
        @Html.Partial(String.Format("Partials/{0}/PlanTable", Model.ViewName), Model.ViewCollection)
    </div>
</div>
<div class="col-md-6 test-field">
    @if (Model.Single != null)
    {
        <div class="title">
            <h4>Аналіз за @Model.SingleDate</h4>
        </div>
        @Html.Partial(String.Format("Partials/{0}/{0}", Model.ViewName), Model.Single)
    }
    else
    {
        <div class="empty-test">
            <h2>Аналіз не обрано</h2>
        </div>
    }
</div>

TubNet2/Views/Test/TestsList.cshtml
@model TubNet2.Models.ViewTestsModel

@{
    ViewBag.Title = "TestsList";
}

@Styles.Render("~/Content/TestStyle.css")

<h2>Аналізи пацієнта: @Model.Patient.p_surname @Model.Patient.p_name @Model.Patient.p_secname</h2>

<div class="nav col-md-12">
    @Html.ActionLink("Аналізи крові", "TestsList", new { p_id = Model.Patient.p_id, viewName = "BloodTest", viewType = Model.filter.ViewType }, htmlAttributes: new { @class = (Model.ViewName == "BloodTest") ? "btn btn-primary" : "btn btn-style" })
    @Html.ActionLink("Аналізи сечі", "TestsList", new { p_id = Model.Patient.p_id, viewName = "UrinaTest", viewType = Model.filter.ViewType }, htmlAttributes: new { @class = (Model.ViewName == "UrinaTest") ? "btn btn-primary" : "btn btn-style" })
    @Html.ActionLink("Печінкові проби", "TestsList", new { p_id = Model.Patient.p_id, viewName = "HepaticTest", viewType = Model.filter.ViewType }, htmlAttributes: new { @class = (Model.ViewName == "HepaticTest") ? "btn btn-primary" : "btn btn-style" })
    @Html.ActionLink("Аналізи мокроти", "TestsList", new { p_id = Model.Patient.p_id, viewName = "SputumTest", viewType = Model.filter.ViewType }, htmlAttributes: new { @class = (Model.ViewName == "SputumTest") ? "btn btn-primary" : "btn btn-style" })
    @Html.ActionLink("Консультація", "TestsList", new { p_id = Model.Patient.p_id, viewName = "Consultation", viewType = Model.filter.ViewType }, htmlAttributes: new { @class = (Model.ViewName == "Consultation") ? "btn btn-primary" : "btn btn-style" })
</div>


<div class="col-md-3">
    <br />
    @Html.ActionLink("Повернутися до пацієнта", "SinglePatient", "Patient", new { p_id = Model.Patient.p_id }, htmlAttributes: new { @class = "btn btn-style" })
    <br />
    <div class="filter">
        <div class="title">
            <h4>Фільтр</h4>
        </div>
        <div class="inside">
            @Html.Partial("Partials/Filter", Model.filter)
        </div>
    </div>
    <br />

</div>

<div class="col-md-9 content">
    @Html.Partial(Model.filter.ViewType, Model)
</div>